package edu.cs371m.triviagame.database

import com.google.firebase.Timestamp
import com.google.firebase.firestore.DocumentId
import com.google.firebase.firestore.ServerTimestamp

// Firebase insists we have a no argument constructor
data class UserData(
    // Auth information
    var ownerName: String = "",
    var ownerUid: String = "",
    var uuid : String = "",
    var score: Int = 0,
    // Written on the server
    @ServerTimestamp val timeStamp: Timestamp? = null,
    // firestoreID is generated by firestore, used as primary key
    @DocumentId var firestoreID: String = ""
)